# Generated by Django 5.1.2 on 2024-10-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0002_alter_bookmark_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='notes',
            field=models.CharField(max_length=50),
        ),
    ]
