# Generated by Django 5.1.2 on 2024-10-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0003_alter_bookmark_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='notes',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
