# Generated by Django 5.1.2 on 2024-10-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0009_alter_product_image'),
        ('forum', '0003_alter_forum_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='recommendations',
        ),
        migrations.AddField(
            model_name='forum',
            name='recommendations',
            field=models.ManyToManyField(blank=True, to='Homepage.restaurant'),
        ),
    ]
