# Generated by Django 5.1 on 2024-10-26 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0007_restaurant_image'),
        ('Review', '0003_remove_review_image_alter_review_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Homepage.restaurant'),
        ),
    ]
