# Generated by Django 5.1 on 2024-10-26 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0007_restaurant_image'),
        ('Review', '0005_alter_review_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='Homepage.restaurant'),
        ),
    ]
