# Generated by Django 5.1.2 on 2024-10-24 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaliLoka_stories', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stories',
            new_name='StoriesEntry',
        ),
    ]
