# Generated by Django 5.1.2 on 2024-10-23 08:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaliLoka_stories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoriesEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Stories',
        ),
    ]
