# Generated by Django 5.1.2 on 2024-10-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaliLoka_stories', '0002_rename_stories_storiesentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storiesentry',
            name='image',
            field=models.ImageField(upload_to='image_coba/'),
        )
    ]
