# Generated by Django 5.1.2 on 2024-10-26 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaliLoka_stories', '0002_storiesentry_delete_stories'),
        ('BaliLoka_stories', '0004_alter_storiesentry_image'),
    ]

    operations = [
    ]
